server:
  port: 1000

spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream